#!/bin/bash
CURRENT_KERNEL=$(uname -r)

# Command lifted from http://askubuntu.com/a/142937
UNUSED_KERNELS=$(dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d;/^linux-\(headers\|image\)/!d')

echo "Current kernel: $CURRENT_KERNEL"
echo "Unused versions: "
for KERNEL in $UNUSED_KERNELS; do
    echo "  $KERNEL"
done

read -p "Remove (y/N)? " PROCEED; echo
if [ "$PROCEED" = "y" ]; then
    sudo apt-get remove $UNUSED_KERNELS
fi
