#!/bin/bash
TRIGGER=alert
VALUE_1="$@"

if [ -z $IFTTT_KEY ]; then
    echo "A IFTTT_KEY value must be configured in your environment."
    exit 1
fi

curl -XPOST -H "Content-Type: application/json" -d "{\"value1\":\"$VALUE_1\"}" https://maker.ifttt.com/trigger/$TRIGGER/with/key/$IFTTT_KEY 
